### PR TITLE
Handle runtime SMTP errors gracefully in email executor

### LINKED ISSUE #2066: Runtime SMTP errors from invalid email config are not handled gracefully — causes hard flow failures
### Description

When the email client is configured with syntactically valid but semantically wrong values (e.g., unreachable SMTP host, wrong port, incorrect credentials), the initialization succeeds and emailClient is non-nil. The static validation in newSMTPClient() only checks format correctness (non-empty host, port > 0, valid sender address) — it does not verify connectivity.

As a result, the runtime SMTP errors (ErrorSMTPConnection, ErrorSMTPAuth, ErrorEmailSendFailed) surface when Send() is called during flow execution. These errors are not included in isEmailClientError(), so they are not treated as graceful failures — they propagate as hard errors and stop the flow entirely.

### Root Cause:

isEmailClientError() in email_executor.go only covers static config validation errors:

func isEmailClientError(err error) bool {
    return errors.Is(err, email.ErrorInvalidRecipient) ||
        errors.Is(err, email.ErrorInvalidSender) ||
        errors.Is(err, email.ErrorInvalidSubject) ||
        errors.Is(err, email.ErrorInvalidHost) ||
        errors.Is(err, email.ErrorInvalidPort) ||
        errors.Is(err, email.ErrorInvalidCredentials)
}
ErrorSMTPConnection, ErrorSMTPAuth, and ErrorEmailSendFailed are missing, so they fall through to:

return nil, fmt.Errorf("email send failed: %w", err)
This causes a hard error that stops flow execution instead of a graceful degradation.

### Expected Behavior:

SMTP transport errors should be treated the same way as config validation errors — the executor should return ExecFailure with emailSent=false and allow the flow to continue, rather than propagating a hard error.

ErrorSMTPConnection, ErrorSMTPAuth, and ErrorEmailSendFailed should be included in isEmailClientError().

Optionally, the initialization in servicemanager.go could also perform a basic SMTP connectivity check (e.g., dial the host) so misconfigured clients are caught at startup and set to nil, consistent with how config validation errors are handled today.

### Steps to Reproduce

1. Configure SMTP with a syntactically valid but unreachable host (e.g., host: "smtp.nonexistent.example.com", port: 587)
2. Start the server — it starts successfully, emailClient is non-nil
3. Trigger a flow that invokes the email executor
4. Observe a hard runtime error stopping the flow instead of a graceful emailSent=false

### Version

0.30.0

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by ThaminduR**
### Purpose

When the email client is configured with syntactically valid but semantically wrong SMTP values (e.g., unreachable host, wrong credentials), `Send()` returns runtime errors (`ErrorSMTPConnection`, `ErrorSMTPAuth`, `ErrorEmailSendFailed`) that were not recognized by `isEmailClientError()`. These errors propagated as hard failures, stopping flow execution entirely instead of allowing graceful degradation with `emailSent=false`.

### Approach

Added the three missing SMTP transport error types (`ErrorSMTPConnection`, `ErrorSMTPAuth`, `ErrorEmailSendFailed`) to the error check function. Renamed `isEmailClientError()` to `isEmailError()` since it now covers both client-side validation errors and server-side SMTP transport errors.

With this change, all email subsystem errors are treated as graceful failures: the executor returns `ExecFailure` with `emailSent=false`, allowing the flow to continue and the SDK to fall back to displaying the invite link.

### Related Issues
- Fixes #2066

### Related PRs
- N/A

### Checklist
- [x] Followed the contribution guidelines.
- [x] Manual test round performed and verified.
- [ ] Documentation provided. (Add links if there are any)
    - [ ] Ran Vale and fixed all errors and warnings
- [x] Tests provided. (Add links if there are any)
    - [x] Unit Tests
    - [ ] Integration Tests
- [ ] Breaking changes. (Fill if applicable)
    - [ ] Breaking changes section filled.
    - [ ] `breaking change` label added.

### Security checks
- [x] Followed secure coding standards in [WSO2 Secure Coding Guidelines](https://security.docs.wso2.com/en/latest/security-guidelines/secure-engineering-guidelines/secure-coding-guidlines/introduction/)
- [x] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.

## Summary by CodeRabbit

* **Bug Fixes**
  * Email delivery failures are now classified more broadly across validation and SMTP transport errors; failures produce consistent "Failed to send email" responses and improved error logging for easier diagnosis.
  * Unexpected internal send errors now surface as execution errors rather than being treated as known send failures.

* **Tests**
  * Expanded tests covering SMTP connection, authentication, send failures, and unexpected internal errors.

### CODE REVIEW

File: backend/internal/flow/executor/email_executor.go [hunk 1]
```diff
@@ -141,7 +141,7 @@ func (e *emailExecutor) executeSend(ctx *core.NodeContext) (*common.ExecutorResp
 	}
 
 	if err := e.emailClient.Send(emailData); err != nil {
-		if isEmailClientError(err) {
+		if isEmailError(err) {
 			execResp.Status = common.ExecFailure
```
Comment (rajithacharith) [inline backend/internal/flow/executor/email_executor.go:144]: The initial implementation creates a flow exec error without logging the error. This will mask the original error which will complicate the root cause analysis when debugging. 
Shall we log the error 
```suggestion
            logger.Error("Error sending mail : ", log.Error(err))
			execResp.Status = common.ExecFailure
```

**Review by ThaminduDilshan — APPROVED** [review]
