### PR TITLE
Fix missing clientId in Windows bootstrap for Console app

### LINKED ISSUE #1992: Fix missing clientId in Windows bootstrap script for Console application
## Description

The Windows (PowerShell) bootstrap script `01-default-resources.ps1` uses **snake_case** keys in the Console application creation payload, while the API expects **camelCase** (matching the macOS/Linux bash script `01-default-resources.sh`).

This causes the Console application to be created **without a clientId** on Windows, while it works correctly on macOS/Linux.

## Root Cause

In `backend/cmd/server/bootstrap/01-default-resources.ps1`, the Console application hashtable (around line 1190) used snake_case keys:

```powershell
$appData = @{
    ...
    logo_url = "emoji:👨‍💻"
    auth_flow_id = $CONSOLE_AUTH_FLOW_ID
    registration_flow_id = $CONSOLE_REG_FLOW_ID
    is_registration_flow_enabled = $false
    allowed_user_types = @("Person")
    inbound_auth_config = @(
        @{
            type = "oauth2"
            config = @{
                client_id = "CONSOLE"          # API expects "clientId"
                redirect_uris = ...
                grant_types = ...
                ...
            }
        }
    )
}
```

The bash script (`01-default-resources.sh`) correctly uses camelCase:
```json
{
    "clientId": "CONSOLE",
    "redirectUris": [...],
    "inboundAuthConfig": [...]
}
```

## Affected Keys

| PowerShell (broken) | Bash / API (correct) |
|---|---|
| `client_id` | `clientId` |
| `redirect_uris` | `redirectUris` |
| `inbound_auth_config` | `inboundAuthConfig` |
| `auth_flow_id` | `authFlowId` |
| `registration_flow_id` | `registrationFlowId` |
| `is_registration_flow_enabled` | `isRegistrationFlowEnabled` |
| `allowed_user_types` | `allowedUserTypes` |
| `logo_url` | `logoUrl` |
| `grant_types` | `grantTypes` |
| `response_types` | `responseTypes` |
| `pkce_required` | `pkceRequired` |
| `token_endpoint_auth_method` | `tokenEndpointAuthMethod` |
| `public_client` | `publicClient` |
| `access_token` | `accessToken` |
| `id_token` | `idToken` |
| `validity_period` | `validityPeriod` |
| `scope_claims` | `scopeClaims` |

## Fix

Update all snake_case keys in the Console application payload to camelCase to match the API contract and the bash script.

## Impact

- **Windows users** cannot log into the Console after bootstrap because the OAuth2 client has no clientId set.
- **macOS/Linux users** are unaffected.

### PR DESCRIPTION
**Pull request by DonOmalVindula**
## Summary

- Fix the PowerShell bootstrap script (`01-default-resources.ps1`) Console application payload using snake_case keys instead of camelCase
- This caused the Console app to be created without a `clientId` on Windows, while macOS/Linux worked correctly

## Changes

Updated all snake_case keys in the Console application creation payload to camelCase to match the API contract and the bash script (`01-default-resources.sh`):

`client_id` → `clientId`, `redirect_uris` → `redirectUris`, `inbound_auth_config` → `inboundAuthConfig`, `auth_flow_id` → `authFlowId`, `registration_flow_id` → `registrationFlowId`, `is_registration_flow_enabled` → `isRegistrationFlowEnabled`, `allowed_user_types` → `allowedUserTypes`, `logo_url` → `logoUrl`, `grant_types` → `grantTypes`, `response_types` → `responseTypes`, `pkce_required` → `pkceRequired`, `token_endpoint_auth_method` → `tokenEndpointAuthMethod`, `public_client` → `publicClient`, `access_token` → `accessToken`, `id_token` → `idToken`, `validity_period` → `validityPeriod`, `user_attributes` → `userAttributes`, `scope_claims` → `scopeClaims`

Fixes #1992

### CODE REVIEW

**Review by KaveeshaPiumini — DISMISSED** [review]

File: backend/internal/userschema/model/schema.go [hunk 1]
```diff
@@ -155,7 +155,9 @@ func (cs *Schema) Validate(attributes json.RawMessage, logger *log.Logger) (bool
 	for propName, prop := range cs.properties {
 		value, exists := userAttrs[propName]
 		if !exists {
-			if prop.isRequired() {
+			// Credential properties are extracted before validation, so skip the
+			// required check for them to avoid false negatives.
+			if prop.isRequired() && !prop.isCredential() {
```
Comment (ThaminduDilshan) [inline backend/internal/userschema/model/schema.go]: I feel like this will skip the validation during the user creation.

During user creation, we're passing the entire attribute payload to the `validateUserAndUniqueness` function [1] which then calls the userSchemaService.ValidateUser() method. It calls this method to validate attributes against the schema [2]. With this fix we'll lose the required field validation for the credentials in the user creation payload right?

[1] https://github.com/asgardeo/thunder/blob/9422ba014db04d70652f9484cdac901c9c970011/backend/internal/user/service.go#L327
[2] https://github.com/asgardeo/thunder/blob/9422ba014db04d70652f9484cdac901c9c970011/backend/internal/userschema/service.go#L498

Comment (ThaminduDilshan) [reply backend/internal/userschema/model/schema.go]: [Not related to this PR] 
Additionally we're extracting out credential attributes during user update request before calling this method. And it looks like credential attributes are never validated against the schema due to that logic.

Comment (DonOmalVindula) [reply backend/internal/userschema/model/schema.go]: Will send a separate PR for this
